import { expect, test } from '@playwright/test';
import { fixtureUsers } from './support/cassette-fixtures';
import { mockCassetteApp } from './support/mock-cassette-app';
import { mockRedditCompetitions } from './support/mock-reddit-competitions';

test('review, edit, preserve failed saves, and explicitly queue a saved announcement', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1080 });
  await mockCassetteApp(page, { currentUser: { ...fixtureUsers.member, accountType: 'CassetteTeam' } });
  const state = await mockRedditCompetitions(page);
  await page.goto('/internal');
  await page.getByRole('navigation').getByRole('link', { name: 'Marketing', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Automations', exact: true })).toBeVisible();
  await page.screenshot({ path: '/tmp/cassette-marketing-automations-desktop.png', fullPage: true });
  await page.getByRole('link', { name: /Weekly playlist competition/ }).click();
  await expect(page).toHaveURL('/internal/marketing/automations/reddit');
  await expect(page.getByRole('heading', { name: 'Weekly playlist competition', exact: true, level: 1 })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'First place: Weekend selections' })).toBeVisible();
  const savedBody = state.round.body;
  await page.getByRole('button', { name: 'Apply template', exact: true }).click();
  await page.getByRole('button', { name: 'Keep current text' }).click();
  expect(state.round.body).toBe(savedBody);
  await page.getByRole('button', { name: 'Apply template', exact: true }).click();
  await page.getByRole('button', { name: 'Replace text', exact: true }).click();
  await expect(page.getByRole('heading', { name: '9/18/26 | Week 2 Playlist Competition Winners' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Post to Reddit', exact: true })).toBeDisabled();
  expect(state.round.body).toBe(savedBody);
  await page.getByRole('button', { name: 'Discard edits', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'First place: Weekend selections' })).toBeVisible();
  await page.getByRole('tab', { name: 'Edit', exact: true }).click();
  await page.getByRole('textbox', { name: 'Announcement (Markdown)', exact: true }).fill('## Winner\n\nAn edited review.\n\n[Listen on Cassette](https://dev.cassette.tech/post/p_example)');
  await expect(page.getByRole('button', { name: 'Post to Reddit', exact: true })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Competition round', exact: true })).toBeDisabled();
  state.failSave = true;
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Another team member' })).toContainText('Another team member');
  await expect(page.getByRole('textbox', { name: 'Announcement (Markdown)', exact: true })).toHaveValue('## Winner\n\nAn edited review.\n\n[Listen on Cassette](https://dev.cassette.tech/post/p_example)');
  state.failSave = false;
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Post to Reddit', exact: true })).toBeEnabled();
  await page.getByRole('tab', { name: 'Preview', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Winner', exact: true })).toBeVisible();
  await page.getByRole('heading', { name: 'Weekly playlist competition', exact: true, level: 1 }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: '/tmp/cassette-competition-console-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Post to Reddit', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirm and queue post' })).toBeDisabled();
  await page.getByLabel('I reviewed the announcement and confirmed the selected winners.').check();
  await page.getByLabel('How were the selection issues resolved?').fill('Selected the original entry and excluded the duplicate.');
  await page.getByRole('button', { name: 'Confirm and queue post' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Approved and queued.' })).toBeVisible();
  expect(state.approvals).toBe(1);
  await expect(page.getByRole('link', { name: 'View Reddit post' })).toHaveCount(0);
  state.round.status = 'published'; state.round.postId = 't3_published';
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.getByRole('link', { name: 'View Reddit post' })).toHaveAttribute('href', 'https://www.reddit.com/comments/published');
  await page.getByRole('link', { name: 'All automations', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Automations', exact: true })).toBeVisible();
});

test('weekly settings and review remain usable on a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await mockCassetteApp(page, { currentUser: { ...fixtureUsers.member, accountType: 'CassetteTeam' } });
  const state = await mockRedditCompetitions(page);
  await page.goto('/internal/marketing');
  await expect(page.getByRole('heading', { name: 'Automations', exact: true })).toBeVisible();
  await page.screenshot({ path: '/tmp/cassette-marketing-automations-mobile.png', fullPage: true });
  await page.getByRole('link', { name: /Weekly playlist competition/ }).click();
  await page.locator('summary:visible').filter({ hasText: 'Weekly drafts: Paused' }).click();
  await page.getByRole('checkbox', { name: 'Prepare a draft every week' }).check();
  await page.getByRole('combobox', { name: 'Day', exact: true }).selectOption('1');
  await page.getByLabel('Time', { exact: true }).filter({ visible: true }).fill('09:00');
  await page.getByLabel('Week 1 announcement date', { exact: true }).filter({ visible: true }).fill('2026-08-09');
  await page.getByRole('textbox', { name: 'Introduction', exact: true }).fill('Welcome to r/{subreddit}!');
  await page.getByRole('button', { name: 'Save settings' }).click();
  await expect(page.locator('summary:visible').filter({ hasText: 'Weekly drafts: Monday, 09:00 America/New_York' })).toBeVisible();
  expect(state.community.enabled).toBe(true);
  expect(state.community.weekOneDate).toBe('2026-08-09');
  expect(state.community.introduction).toBe('Welcome to r/{subreddit}!');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/cassette-competition-console-mobile.png', fullPage: true });
  state.round.body = ''; state.round.candidates = []; state.round.selectedPostIds = [];
  state.round.issues = ['No eligible playlists were found.'];
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Selection review' }).getByText('No eligible playlists were found.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Post to Reddit', exact: true })).toBeDisabled();
});

test('selected winner conversions show failures, support retry, and block publication until ready', async ({ page }) => {
  await mockCassetteApp(page, { currentUser: { ...fixtureUsers.member, accountType: 'CassetteTeam' } });
  const state = await mockRedditCompetitions(page);
  const candidate = state.round.candidates[0];
  candidate.cassettePostId = null; candidate.cassetteUrl = null;
  candidate.conversionError = 'Playlist conversion failed (PLAYLIST_NOT_FOUND). Retry or select another winner.';
  await page.goto('/internal/marketing/automations/reddit');
  await expect(page.getByRole('alert').filter({ hasText: 'PLAYLIST_NOT_FOUND' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Post to Reddit', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Retry conversion', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Edit', exact: true })).toBeDisabled();
  await expect(page.getByRole('status').filter({ hasText: 'The bot is preparing Cassette links' })).toBeVisible();
  expect(candidate.conversionAttempt).toBe(1);
  candidate.cassettePostId = 'p_example'; candidate.cassetteUrl = 'https://dev.cassette.tech/post/p_example';
  state.round.body = state.round.body.replace('https://open.spotify.com/playlist/example', candidate.cassetteUrl);
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.getByRole('link', { name: 'View Cassette playlist', exact: true })).toHaveAttribute('href', candidate.cassetteUrl);
  await expect(page.getByRole('tab', { name: 'Edit', exact: true })).toBeEnabled();
  await expect(page.getByRole('button', { name: 'Post to Reddit', exact: true })).toBeEnabled();
});

test('uncertain publication is resolved only by an explicit team decision', async ({ page }) => {
  await mockCassetteApp(page, { currentUser: { ...fixtureUsers.member, accountType: 'CassetteTeam' } });
  const state = await mockRedditCompetitions(page);
  Object.assign(state.round, { status: 'publication_uncertain', error: 'No single published post was confirmed in the latest 100 posts.' });
  await page.goto('/internal/marketing/automations/reddit');
  await page.getByRole('textbox', { name: 'Reddit post link', exact: true }).fill('not a link');
  await page.getByRole('button', { name: 'Mark as published', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Enter the Reddit post link' })).toBeVisible();
  expect(state.round.status).toBe('publication_uncertain');
  await page.getByRole('button', { name: 'Nothing was posted', exact: true }).click();
  await page.getByRole('button', { name: 'Keep current state', exact: true }).click();
  expect(state.round.status).toBe('publication_uncertain');
  await page.getByRole('textbox', { name: 'Reddit post link', exact: true }).fill('https://www.reddit.com/r/cassette_bot_dev/comments/abc123/weekly_winners/');
  await page.getByRole('button', { name: 'Mark as published', exact: true }).click();
  await expect(page.getByRole('link', { name: 'View Reddit post' })).toHaveAttribute('href', 'https://www.reddit.com/comments/abc123');
  expect(state.round.postId).toBe('t3_abc123');
});
